/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jeffrey
 */
public class RobotGUI extends javax.swing.JFrame {

    Cell[][] grid;
    /**
     * Creates new form RobotGUI
     */
    public RobotGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cell4 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cell3 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        cell5 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        cell2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        cell1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        cell10 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        cell9 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        cell8 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        cell7 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        cell15 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        cell6 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        cell13 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        cell14 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        cell11 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        cell20 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        cell12 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        cell25 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        cell19 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        cell17 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        cell18 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        cell16 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        cell24 = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        cell23 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        cell21 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        cell22 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        clock = new javax.swing.JTextField();
        start_button = new javax.swing.JButton();
        stop_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reinforcement Learning");
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.blue);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));

        cell4.setEditable(false);
        cell4.setBackground(java.awt.Color.lightGray);
        cell4.setBorder(new javax.swing.border.MatteBorder(null));
        cell4.setText("          0\n\n0                  0\n\n          0");
        jScrollPane1.setViewportView(cell4);

        cell3.setEditable(false);
        cell3.setBackground(java.awt.Color.lightGray);
        cell3.setBorder(new javax.swing.border.MatteBorder(null));
        cell3.setText("          0\n\n0                  0\n\n          0");
        jScrollPane2.setViewportView(cell3);

        cell5.setEditable(false);
        cell5.setBackground(java.awt.Color.lightGray);
        cell5.setBorder(new javax.swing.border.MatteBorder(null));
        cell5.setText("          0\n\n0                  0\n\n          0");
        jScrollPane3.setViewportView(cell5);

        cell2.setEditable(false);
        cell2.setBackground(java.awt.Color.lightGray);
        cell2.setBorder(new javax.swing.border.MatteBorder(null));
        cell2.setText("          0\n\n0                  0\n\n          0");
        jScrollPane4.setViewportView(cell2);

        cell1.setEditable(false);
        cell1.setBackground(java.awt.Color.lightGray);
        cell1.setBorder(new javax.swing.border.MatteBorder(null));
        cell1.setText("          0\n\n0                  0\n\n          0");
        jScrollPane5.setViewportView(cell1);

        cell10.setEditable(false);
        cell10.setBackground(java.awt.Color.lightGray);
        cell10.setBorder(new javax.swing.border.MatteBorder(null));
        cell10.setText("          0\n\n0                  0\n\n          0");
        jScrollPane6.setViewportView(cell10);

        cell9.setEditable(false);
        cell9.setBackground(java.awt.Color.lightGray);
        cell9.setBorder(new javax.swing.border.MatteBorder(null));
        cell9.setText("          0\n\n0                  0\n\n          0");
        jScrollPane7.setViewportView(cell9);

        cell8.setEditable(false);
        cell8.setBackground(java.awt.Color.lightGray);
        cell8.setBorder(new javax.swing.border.MatteBorder(null));
        cell8.setText("          0\n\n0                  0\n\n          0");
        jScrollPane8.setViewportView(cell8);

        cell7.setEditable(false);
        cell7.setBackground(java.awt.Color.lightGray);
        cell7.setBorder(new javax.swing.border.MatteBorder(null));
        cell7.setText("          0\n\n0                  0\n\n          0");
        jScrollPane9.setViewportView(cell7);

        cell15.setEditable(false);
        cell15.setBackground(java.awt.Color.lightGray);
        cell15.setBorder(new javax.swing.border.MatteBorder(null));
        cell15.setText("          0\n\n0                  0\n\n          0");
        jScrollPane10.setViewportView(cell15);

        cell6.setEditable(false);
        cell6.setBackground(java.awt.Color.lightGray);
        cell6.setBorder(new javax.swing.border.MatteBorder(null));
        cell6.setText("          0\n\n0                  0\n\n          0");
        jScrollPane11.setViewportView(cell6);

        cell13.setEditable(false);
        cell13.setBackground(java.awt.Color.lightGray);
        cell13.setBorder(new javax.swing.border.MatteBorder(null));
        cell13.setText("          0\n\n0                  0\n\n          0");
        jScrollPane12.setViewportView(cell13);

        cell14.setEditable(false);
        cell14.setBackground(java.awt.Color.lightGray);
        cell14.setBorder(new javax.swing.border.MatteBorder(null));
        cell14.setText("          0\n\n0                  0\n\n          0");
        jScrollPane13.setViewportView(cell14);

        cell11.setEditable(false);
        cell11.setBackground(java.awt.Color.lightGray);
        cell11.setBorder(new javax.swing.border.MatteBorder(null));
        cell11.setText("          0\n\n0                  0\n\n          0");
        jScrollPane14.setViewportView(cell11);

        cell20.setEditable(false);
        cell20.setBackground(java.awt.Color.lightGray);
        cell20.setBorder(new javax.swing.border.MatteBorder(null));
        cell20.setText("          0\n\n0                  0\n\n          0");
        jScrollPane15.setViewportView(cell20);

        cell12.setEditable(false);
        cell12.setBackground(java.awt.Color.lightGray);
        cell12.setBorder(new javax.swing.border.MatteBorder(null));
        cell12.setText("          0\n\n0                  0\n\n          0");
        jScrollPane16.setViewportView(cell12);

        cell25.setEditable(false);
        cell25.setBackground(java.awt.Color.lightGray);
        cell25.setBorder(new javax.swing.border.MatteBorder(null));
        cell25.setText("          0\n\n0                  0\n\n          0");
        jScrollPane17.setViewportView(cell25);

        cell19.setEditable(false);
        cell19.setBackground(java.awt.Color.lightGray);
        cell19.setBorder(new javax.swing.border.MatteBorder(null));
        cell19.setText("          0\n\n0                  0\n\n          0");
        jScrollPane18.setViewportView(cell19);

        cell17.setEditable(false);
        cell17.setBackground(java.awt.Color.lightGray);
        cell17.setBorder(new javax.swing.border.MatteBorder(null));
        cell17.setText("          0\n\n0                  0\n\n          0");
        jScrollPane19.setViewportView(cell17);

        cell18.setEditable(false);
        cell18.setBackground(java.awt.Color.lightGray);
        cell18.setBorder(new javax.swing.border.MatteBorder(null));
        cell18.setText("          0\n\n0                  0\n\n          0");
        jScrollPane20.setViewportView(cell18);

        cell16.setEditable(false);
        cell16.setBackground(java.awt.Color.lightGray);
        cell16.setBorder(new javax.swing.border.MatteBorder(null));
        cell16.setText("          0\n\n0                  0\n\n          0");
        jScrollPane21.setViewportView(cell16);

        cell24.setEditable(false);
        cell24.setBackground(java.awt.Color.lightGray);
        cell24.setBorder(new javax.swing.border.MatteBorder(null));
        cell24.setText("          0\n\n0                  0\n\n          0");
        jScrollPane22.setViewportView(cell24);

        cell23.setEditable(false);
        cell23.setBackground(java.awt.Color.lightGray);
        cell23.setBorder(new javax.swing.border.MatteBorder(null));
        cell23.setText("          0\n\n0                  0\n\n          0");
        jScrollPane23.setViewportView(cell23);

        cell21.setEditable(false);
        cell21.setBackground(java.awt.Color.lightGray);
        cell21.setBorder(new javax.swing.border.MatteBorder(null));
        cell21.setText("          0\n\n0                  0\n\n          0");
        jScrollPane24.setViewportView(cell21);

        cell22.setEditable(false);
        cell22.setBackground(java.awt.Color.lightGray);
        cell22.setBorder(new javax.swing.border.MatteBorder(null));
        cell22.setText("          0\n\n0                  0\n\n          0");
        jScrollPane25.setViewportView(cell22);

        jPanel2.setBackground(java.awt.Color.yellow);

        clock.setEditable(false);
        clock.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        clock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clock.setText("00:00:00");

        start_button.setText("Start");

        stop_button.setText("Stop");

        reset_button.setText("Reset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(start_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stop_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stop_button)
                .addGap(18, 18, 18)
                .addComponent(reset_button)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {reset_button, start_button, stop_button});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane10, jScrollPane11, jScrollPane12, jScrollPane13, jScrollPane14, jScrollPane15, jScrollPane16, jScrollPane17, jScrollPane18, jScrollPane19, jScrollPane2, jScrollPane20, jScrollPane21, jScrollPane22, jScrollPane23, jScrollPane24, jScrollPane25, jScrollPane3, jScrollPane4, jScrollPane5, jScrollPane6, jScrollPane7, jScrollPane8, jScrollPane9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane10, jScrollPane11, jScrollPane12, jScrollPane13, jScrollPane14, jScrollPane15, jScrollPane16, jScrollPane17, jScrollPane18, jScrollPane19, jScrollPane2, jScrollPane20, jScrollPane21, jScrollPane22, jScrollPane23, jScrollPane24, jScrollPane25, jScrollPane3, jScrollPane4, jScrollPane5, jScrollPane6, jScrollPane7, jScrollPane8, jScrollPane9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RobotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RobotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RobotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RobotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RobotGUI().setVisible(true);
            }
        });
    }
    
    /**
     * @param new_grid 
     * update the cells of the gui with the cells from the algo
     */
    public void updateCells(Cell[][] new_grid){
        grid = new_grid;
        cell1.setText(grid[0][0].toString());
        cell2.setText(grid[0][1].toString());
        cell3.setText(grid[0][2].toString());
        cell4.setText(grid[0][3].toString());
        cell5.setText(grid[0][4].toString());
        
        cell6.setText(grid[1][0].toString());
        cell7.setText(grid[1][1].toString());
        cell8.setText(grid[1][2].toString());
        cell9.setText(grid[1][3].toString());
        cell10.setText(grid[1][4].toString());
        
        cell11.setText(grid[2][0].toString());
        cell12.setText(grid[2][1].toString());
        cell13.setText(grid[2][2].toString());
        cell14.setText(grid[2][3].toString());
        cell15.setText(grid[2][4].toString());
        
        cell16.setText(grid[3][0].toString());
        cell17.setText(grid[3][1].toString());
        cell18.setText(grid[3][2].toString());
        cell19.setText(grid[3][3].toString());
        cell20.setText(grid[3][4].toString());
        
        cell21.setText(grid[4][0].toString());
        cell22.setText(grid[4][1].toString());
        cell23.setText(grid[4][2].toString());
        cell24.setText(grid[4][3].toString());
        cell25.setText(grid[4][4].toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cell1;
    private javax.swing.JTextPane cell10;
    private javax.swing.JTextPane cell11;
    private javax.swing.JTextPane cell12;
    private javax.swing.JTextPane cell13;
    private javax.swing.JTextPane cell14;
    private javax.swing.JTextPane cell15;
    private javax.swing.JTextPane cell16;
    private javax.swing.JTextPane cell17;
    private javax.swing.JTextPane cell18;
    private javax.swing.JTextPane cell19;
    private javax.swing.JTextPane cell2;
    private javax.swing.JTextPane cell20;
    private javax.swing.JTextPane cell21;
    private javax.swing.JTextPane cell22;
    private javax.swing.JTextPane cell23;
    private javax.swing.JTextPane cell24;
    private javax.swing.JTextPane cell25;
    private javax.swing.JTextPane cell3;
    private javax.swing.JTextPane cell4;
    private javax.swing.JTextPane cell5;
    private javax.swing.JTextPane cell6;
    private javax.swing.JTextPane cell7;
    private javax.swing.JTextPane cell8;
    private javax.swing.JTextPane cell9;
    private javax.swing.JTextField clock;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton start_button;
    private javax.swing.JButton stop_button;
    // End of variables declaration//GEN-END:variables
}
